import type { Metadata } from 'next';
import '../styles/globals.css';
import {ReactNode} from "react";

export const metadata: Metadata = {
    title: 'FastAPI NextJS Auth Application',
    description: 'Generated by create next app',
}

export interface RootLayoutProps {
    children: ReactNode;
}

export default function RootLayout({children}: RootLayoutProps) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
